// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDoqYoA9j_4AaJ_lyXE7aSmb4El6Qu0Gg',
    appId: '1:564099934074:web:d46a93d8aa53b95d5758c3',
    messagingSenderId: '564099934074',
    projectId: 'areniego-firebase',
    authDomain: 'areniego-firebase.firebaseapp.com',
    storageBucket: 'areniego-firebase.appspot.com',
    measurementId: 'G-FLV4NQ86XX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXYk0C1mJ0yXAJsp87ahsVyivpR2cT0Ks',
    appId: '1:564099934074:android:6ed0a537770aaac05758c3',
    messagingSenderId: '564099934074',
    projectId: 'areniego-firebase',
    storageBucket: 'areniego-firebase.appspot.com',
  );
}
